service: aws-node-rest-api-orders-service

provider:
  name: aws
  profile: default
  iamRoleStatements:
      # - Effect: Allow
      #   Action:
      #     - dynamodb:Query
      #     - dynamodb:Scan
      #     - dynamodb:GetItem
      #     - dynamodb:PutItem
      #     - dynamodb:UpdateItem
      #     - dynamodb:DeleteItem
      #   Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_ORDERS}"
      - Effect: Allow
        Action:
          - cognito-idp:AdminGetUser
          - cognito-idp:adminListGroupsForUser
          - cognito-idp:ListUsers
        Resource: "*"
        
functions:
  createOrder:
    handler: createOrder.createOrder
    events:
      - http:
          path: order
          method: post
          cors: true
          authorizer: aws_iam

  hotelList:
    handler: getOrder.getOrder
    events:
      - http:
          path: order
          method: get
          cors: true
          authorizer: aws_iam
  # updateUser:
  #   handler: handler.updateUser
  #   events:
  #     - http:
  #         path: user/{id}
  #         method: put
  #         cors: true

  # deleteUser:
  #   handler: handler.deleteUser
  #   events:
  #     - http:
  #         path: user/{id}
  #         method: delete
  #         cors: true

  # user:
  #   handler: handler.user
  #   events:
  #     - http:
  #         path: user/{id}
  #         method: get
  #         cors: true
